---

- name: Vidage de la table NAT    
  iptables:
    table: nat 
    flush: yes
   
- name: Traduction d'adresses - NAT
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: " enp0s3 "
    source: "{{ ansible_enp0s8.ipv4.network }}/24"
    jump: MASQUERADE

- name: Regle de suivi des connections persistantes
  iptables:
    chain: FORWARD
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  
- name: Sauvegarde de la table NAT 
  shell: iptables-save > /etc/iptables/rules.v4
