---
   
- name: Traduction d'adresses - NAT 
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "enp0s3"
    source: "{{ ansible_enp0s8.ipv4.network }}/24"
    jump: MASQUERADE

- name: Insertion des regles de protocole ESP via le service strongswan
  service:
    name: strongswan
    state: restarted

- name: Sauvegarde des regles NETFILTER 
  shell: iptables-save > /etc/iptables/rules.v4

